---
title: "CodeBook"
author: "Srikanth"
date: "Saturday, February 21, 2015"
output: html_document
---

##CodeBook
###Describes the variables, the data and work that I performed to clean up the data

Variable and data descriptions  
* path  
Path location of the data files. Set to "D:/3. Getting and Cleaning data/UCI HAR Dataset/"  
* features  
The vector containing the names of the columns. Obtained from the file features.txt  
* col_types  
A vector to specify the class of the columns classes to be read in the Xtest.txt file  
* X_test  
A data table containing 561 columns of the various measurements. The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ  
* subject_test  
A table indicating the volunteer who generated those signals mentioned above  
* y_test  
A table which describes the activites of the volunteers in numerals ranging from 1 to 6  
* X_train  
Similar to X_test but generated by volunteers in the training set  
* y_train  
Similar to y_test but generated by volunteers in the training set  
* XTestTrain  
The combined dataset of the tables X_test and X_train  
* tidyData  
The combined dataset of the tables X_test and X_train obtained from XTestTrain but only contains the columns which have column names either standard deviations or means of the measurements; filtered by "[Mm]ean\\(\\)|std\\(\\)". Also, the activites are labeled in this table  
* Averages  
The table obtained from tidyData table which is grouped by each volunteer and each activity and summarized by the means of the rest of the columns in the table  
  
How it works:  
The column names are read from the ytest file using the read.table command. Then the test data is read into Xtest using the same read.table command. The path is obtained from concatenating the path variable and the file names' using the function paste0(). Respondent number is also read and stored in the subjectTest file using read.table. Then the columns are combined into one table using cbind(). In this the column 'set' is added to mention that the observations come from the test data.  
The same process is repeated for the training data.  
Then using an IF ELSE ladder, the activity numbers are renamed into the activity labels.  
After this, the data is grouped by respondent and activity and averages of the rest of the variables are retained in the 'Averages' using the aggregate function.   This table is written into a text file using the write.table into the local which is also attached in the answer.  
Features are normalized and bounded within [-1,1]  
  
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz.   
  
Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).   
  
Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals).   
  
These signals were used to estimate variables of the feature vector for each pattern:    
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.  
  
tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  
  
The set of variables that were estimated from these signals are:  
  
mean(): Mean value  
std(): Standard deviation  
Additional vectors obtained by averaging the signals in a signal window sample.   These are used on the angle() variable:  
  
gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

